export const data = {
  name: 'Preetham Reddy Matta',
  shortName: 'Preetham Reddy',
  title: 'Data Scientist',
  tagline: 'Signal in.\nDecisions out.',
  subTagline: 'Data Scientist Intern at Bolt. I build ML systems that reduce churn, sharpen forecasts, and turn noisy data into competitive advantage.',
  location: 'Cleveland, OH',
  email: 'preethamreddy656@gmail.com',
  phone: '216-418-0205',
  linkedin: 'https://www.linkedin.com/in/preetham-reddy-3381a21ba',
  github: 'https://github.com/preethamreddymatta',

  stats: [
    { value: '10%', label: 'Retention Uplift', sub: 'supply-demand ML at Bolt' },
    { value: '24%', label: 'MAPE Reduction', sub: 'Prophet vs. moving-average baseline' },
    { value: '45%', label: 'Engagement Lift', sub: 'ML-driven segmentation at Cognizant' },
    { value: '15%', label: 'Forecast Accuracy', sub: 'regression modeling at Cognizant' },
  ],

  about: [
    "Data Scientist with 3+ years of end-to-end ML experience — from raw data exploration and feature engineering through model deployment and production monitoring. I own full lifecycle, not just notebooks.",
    "At Bolt, I build LLM-assisted analytics workflows and supply-demand optimization systems that directly move retention and revenue metrics. At Cognizant, I led analytical work that slashed funnel drop-offs from 60% to 10% and eliminated 10 hours a week of manual reporting.",
    "My toolkit spans time-series forecasting (ARIMA, SARIMA, Prophet), geospatial ML, NLP, recommendation systems, and rigorous A/B testing. I care about models that ship — built for interpretability, reliability, and real business alignment.",
  ],

  experience: [
    {
      company: 'Bolt',
      role: 'Data Scientist Intern',
      type: 'Internship',
      period: 'June 2025 – Present',
      location: 'Cleveland, OH',
      color: 'teal' as const,
      bullets: [
        'Developed LLM-assisted analytics workflows for fintech customer behavior analysis, improving customer retention by 10% and cutting revenue churn by 5% on legacy products.',
        'Built scalable ML pipelines using Python, SQL, AWS, Docker, and MLflow to optimize supply-demand marketplace efficiency and improve operational performance by 20%.',
        'Delivered interactive stakeholder dashboards translating complex model outputs into actionable business signals that directly informed product roadmap decisions.',
      ],
    },
    {
      company: 'Cleveland State University',
      role: 'Graduate Teaching Assistant',
      type: 'Part-time',
      period: 'May 2024 – Sep 2024',
      location: 'Cleveland, OH',
      color: 'amber' as const,
      bullets: [
        'Instructed graduate-level SQL including joins, aggregations, indexing, and query performance tuning.',
        'Evaluated database design projects and provided structured feedback on schema normalization and optimization.',
      ],
    },
    {
      company: 'Cleveland State University',
      role: 'Statistics Tutor',
      type: 'Part-time',
      period: 'Jan 2024 – Sep 2024',
      location: 'Cleveland, OH',
      color: 'amber' as const,
      bullets: [
        'Tutored 40+ students across Statistics, Probability, Calculus, and Algebra over three consecutive semesters.',
        'Developed explanation frameworks that measurably improved student performance on quantitative assessments.',
      ],
    },
    {
      company: 'Cognizant',
      role: 'Data Analyst',
      type: 'Full-time',
      period: 'Jul 2021 – Jun 2023',
      location: 'Hyderabad, India',
      color: 'violet' as const,
      bullets: [
        'Conducted comprehensive EDA using advanced visualization and summary statistics, enabling data-driven decisions that drove a 10% revenue increase and 20% operational efficiency improvement.',
        'Built scalable ETL pipelines in Python and SQL to analyze large-scale financial datasets; improved regression-based forecasting accuracy by 15% over a 4-year benchmark.',
        'Created Tableau and Power BI dashboards from Amplitude and Segment data, eliminating 10 hours per week of manual reporting.',
        'Applied hypothesis testing, segmentation analysis, and supervised ML to reduce sign-up drop-offs from 60% to 10% and lift user engagement by 45%.',
      ],
    },
  ],

  projects: [
    {
      title: 'YelpSphere — Geo-Cluster Analysis',
      subtitle: 'Spatial ML · Unsupervised Learning · HDBSCAN',
      description: 'Analyzed 150,000+ Yelp businesses across 600+ cities to uncover hidden geographic structure in ratings, reviews, and category distributions. Compared K-Means, DBSCAN, and HDBSCAN — finding that geographic density, not business attributes, drives over 90% of clustering structure.',
      outcomes: [
        '40% improvement in geographic segmentation accuracy over baseline K-Means',
        'Identified 18 high-density metro clusters and 953 outlier locations using HDBSCAN',
        'Generated geospatial insights via UMAP, heatmaps, and interactive maps',
      ],
      tags: ['Python', 'HDBSCAN', 'UMAP', 'K-Means', 'DBSCAN', 'Geospatial', 'Seaborn'],
      color: 'teal' as const,
      featured: true,
      icon: '🗺️',
      github: 'https://github.com/preethamreddymatta',
    },
    {
      title: 'Walmart Weekly Sales Forecasting',
      subtitle: 'Time-Series · Retail Demand · Prophet',
      description: 'Modeled 143 weeks of sales across 45 stores to build production-grade demand forecasting pipelines. Discovered that external signals — fuel price, CPI, temperature — explain less than 3% of variance, shifting strategy to seasonality-driven modeling. Prophet won on both accuracy and interpretability.',
      outcomes: [
        '24% MAPE reduction vs. moving-average baseline using Prophet',
        'Revealed holiday spikes and store-level variability guiding inventory and staffing decisions',
        'Systematically benchmarked ARIMA, SARIMA, and Prophet across all 45 stores',
      ],
      tags: ['Python', 'Prophet', 'ARIMA', 'SARIMA', 'Matplotlib', 'Pandas', 'Seaborn'],
      color: 'amber' as const,
      featured: true,
      icon: '📈',
      github: 'https://github.com/preethamreddymatta',
    },
    {
      title: 'Amazon A/B Testing & LTV Modeling',
      subtitle: 'Statistical Analysis · Product Analytics',
      description: 'End-to-end pricing strategy analysis on 1,000+ Amazon listings. Designed a statistically rigorous A/B test, built a Customer Lifetime Value model, and delivered a complete engagement and pricing strategy grounded in bootstrap simulations and power analysis.',
      outcomes: [
        'Identified a statistically significant 6% engagement uplift for high-discount products',
        'Revealed top 25% of users contribute 80% of total LTV — enabling precise targeting',
        'Full stats workflow: t-tests, chi-square, confidence intervals, bootstrap, power analysis',
      ],
      tags: ['Python', 'A/B Testing', 'LTV Modeling', 'Bootstrap', 'scipy', 'pandas', 'Seaborn'],
      color: 'violet' as const,
      featured: true,
      icon: '🧪',
      github: 'https://github.com/preethamreddymatta',
    },
    {
      title: 'Uber Fare Prediction — Spatial-Temporal ML',
      subtitle: 'Geospatial ML · Regression · XGBoost',
      description: 'Modeled 190K+ Uber trips using engineered geospatial and temporal features. Systematically benchmarked Linear Regression, Random Forest, and XGBoost — achieving strong spatial prediction accuracy with significant RMSE reduction through haversine distance and pickup zone clustering.',
      outcomes: [
        'R² up to 0.79 with XGBoost after geospatial feature engineering',
        '15% RMSE reduction (5.08 → 4.32) vs. baseline model',
        'Key drivers: haversine distance, time-of-day bins, day-of-week, zone clustering',
      ],
      tags: ['Python', 'XGBoost', 'Random Forest', 'Scikit-learn', 'Geospatial', 'Feature Engineering'],
      color: 'teal' as const,
      featured: false,
      icon: '🚕',
      github: 'https://github.com/preethamreddymatta',
    },
    {
      title: 'Airbnb Recommendation Engine',
      subtitle: 'NLP · Collaborative Filtering · Hybrid Recommender',
      description: 'Built a hybrid recommendation system combining cosine similarity and k-NN on 250K+ Airbnb listings. Incorporated TF-IDF vectorization of listing descriptions with structured features to power both content-based and collaborative filtering paths.',
      outcomes: [
        'Hybrid cosine + kNN pipeline operating on 250K+ listing embeddings',
        'TF-IDF text vectorization capturing semantic similarity across listing descriptions',
        'Modular design supporting both cold-start and returning-user recommendation paths',
      ],
      tags: ['Python', 'TF-IDF', 'kNN', 'Scikit-learn', 'NLP', 'Pandas', 'Cosine Similarity'],
      color: 'amber' as const,
      featured: false,
      icon: '🏠',
      github: 'https://github.com/preethamreddymatta',
    },
  ],

  skills: {
    'ML & Modeling': [
      { name: 'XGBoost / Random Forest', level: 92 },
      { name: 'Neural Networks / LSTM', level: 85 },
      { name: 'ARIMA / SARIMA / Prophet', level: 90 },
      { name: 'NLP (Naïve Bayes, TF-IDF, Embeddings)', level: 84 },
      { name: 'Clustering (HDBSCAN, UMAP, K-Means)', level: 87 },
    ],
    'Statistics & Analysis': [
      { name: 'A/B Testing & Hypothesis Testing', level: 93 },
      { name: 'Customer LTV Modeling', level: 88 },
      { name: 'Segmentation & Clustering', level: 87 },
      { name: 'Regression Analysis', level: 91 },
      { name: 'EDA & Feature Engineering', level: 95 },
    ],
    'Engineering & MLOps': [
      { name: 'Python', level: 95 },
      { name: 'SQL (PostgreSQL / Snowflake)', level: 91 },
      { name: 'MLflow / Experiment Tracking', level: 83 },
      { name: 'AWS SageMaker / EC2', level: 81 },
      { name: 'Docker / FastAPI', level: 79 },
    ],
    'Tools & Platforms': [
      { name: 'Tableau / Power BI', level: 88 },
      { name: 'Matplotlib / Seaborn / UMAP', level: 93 },
      { name: 'R', level: 76 },
      { name: 'Scikit-learn / LLM Pipelines', level: 88 },
      { name: 'Linux / CI-CD / Git', level: 75 },
    ],
  },

  education: [
    {
      school: 'Cleveland State University',
      degree: "Master's in Computer Science",
      period: 'Aug 2023 – May 2025',
      location: 'Cleveland, OH',
    },
    {
      school: 'Keshav Memorial College of Engineering',
      degree: "Bachelor's in Computer Science",
      period: 'Aug 2018 – May 2022',
      location: 'Hyderabad, India',
    },
  ],

  certifications: [
    'Supervised Machine Learning: Regression & Classification — DeepLearning.AI',
    'Advanced Learning Algorithms — DeepLearning.AI',
    'Unsupervised Learning, Recommenders & Reinforcement Learning — DeepLearning.AI',
  ],
}
